### ISSUE TITLE
Update to 0.11.1

### ISSUE THREAD

**Issue by moranje** [timkendrick/monaco-editor#8]
Hi @timkendrick, looks like you have been busy with the latest Monaco update! Any chance you'll update this package to the 0.11.1 version of Monaco? I'm working in a codesandbox and have no control over the webpack config (yet). This is pretty much the only way I know how to run Monaco.

Cheers,

Martien

**Comment by timkendrick** [comment]
Hi there, glad to see this has helped! This project was only ever really a proof of concept, and now that the VSCode guys have released the webpack-compatible version of `monaco-editor` I'm not planning on keeping this repo up to date (I think the codebase has quite a lot has changed since the 0.10 version a few months ago). That leaves two options:

1. If you make a PR to update this repo to use 0.11.1 then I will happily merge it (this might be as simple as updating the git submodules to all the right versions and rebuilding, but who knows…)
2. Alternatively, use [the instructions here](https://github.com/timkendrick/monaco-editor-samples/tree/feature/inline-workers/browser-esm-webpack-bundled-library) to build a one-file standalone version of the official 0.11.1 editor for your own use. If you run that webpack build, it will generate a single `monaco.min.js` file that you can then copy into your project and reference from your HTML file via a `<script>` tag.

**Comment by moranje** [comment]
Went with the latter, thanks for supplying all that.

Martien

**Comment by peterschussheim** [comment]
@timkendrick 👋Thanks for your work on this and the many contributions related to monaco + webpack!  

Perhaps you can provide some guidance on the best way to achieve my goal of having a 'turn-key' `monaco` build that can be used with `create-react-app`, with zero modification.  

Currently, I can use your repo (prior to 0.11 updates) in `create-react-app`.  It works very well; specifically, what I like is that one does not need to serve work scripts on a separate server, but the main advantage is simplicity.

I reviewed the sample you linked to in your second suggestion above and wanted to ask your opinion on how to push that example further.  When I saw your PR merged into the official `monaco` repo I was excited as I thought there would now be an 'official' method to use a single-file build of `monaco` but this was not the case.

What would you recommend?  Thanks!
